<?php

/**
 * Prevent Direct Access
 *
 * @since 0.1
 */
defined('ABSPATH') or die("Restricted access!");

/**
 * Register text domain
 *
 * @since 1.3
 */
function mshighlighter_textdomain() {
    load_plugin_textdomain( MSHIGHLIGHTER_TEXT, false, MSHIGHLIGHTER_DIR . '/languages/' );
}
add_action( 'init', 'mshighlighter_textdomain' );

/**
 * Print direct link to plugin admin page
 *
 * Fetches array of links generated by WP Plugin admin page ( Deactivate | Edit )
 * and inserts a link to the plugin admin page
 *
 * @since  1.3
 * @param  array $links Array of links generated by WP in Plugin Admin page.
 * @return array        Array of links to be output on Plugin Admin page.
 */
function mshighlighter_settings_link( $links ) {
    $page = '<a href="' . admin_url( 'options-general.php?page=my-syntax-highlighter.php' ) .'">' . __( 'Settings', MSHIGHLIGHTER_TEXT ) . '</a>';
    array_unshift( $links, $page );
    return $links;
}
add_filter( 'plugin_action_links_'.MSHIGHLIGHTER_BASE, 'mshighlighter_settings_link' );

/**
 * Print additional links to plugin meta row
 *
 * @since 2.0
 */
function mshighlighter_plugin_row_meta( $links, $file ) {

    if ( strpos( $file, 'my-syntax-highlighter.php' ) !== false ) {

        $new_links = array(
                           'donate' => '<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=8A88KC7TFF6CS" target="_blank"><span class="dashicons dashicons-heart"></span> ' . __( 'Donate', MSHIGHLIGHTER_TEXT ) . '</a>'
                           );
        $links = array_merge( $links, $new_links );
    }

    return $links;
}
add_filter( 'plugin_row_meta', 'mshighlighter_plugin_row_meta', 10, 2 );

/**
 * Register plugin's submenu in the "Settings" Admin Menu
 *
 * @since 2.0
 */
function mshighlighter_register_submenu_page() {
    add_options_page( __( 'My Syntax Highlighter', MSHIGHLIGHTER_TEXT ), __( 'Syntax Highlighter', MSHIGHLIGHTER_TEXT ), 'manage_options', 'my-syntax-highlighter', 'mshighlighter_render_submenu_page' );
}
add_action( 'admin_menu', 'mshighlighter_register_submenu_page' );

/**
 * Register settings
 *
 * @since 2.0
 */
function mshighlighter_register_settings() {
    register_setting( 'mshighlighter_settings_group', 'mshighlighter_settings' );
    register_setting( 'mshighlighter_settings_group', 'mshighlighter_service_info' );
}
add_action( 'admin_init', 'mshighlighter_register_settings' );
